### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by ShayBox** [GeyserMC/MCProtocolLib#428]
I realize this isn't an "issue" but since there isn't a support path, this is the best place to ask.
Still fairly new to java, but I'm trying to rewrite something I wrote in javascript.
It's a proxy, it hosts a server, you connect to it, then it creates a client on another server, and sends the packets between the two clients. I know I will have to filter out some packet types for it to work in the end, but I was wondering if this is how I would go about that, and if theirs a faster way than sending each package, on the other lib in javascript it was faster to use a raw instead of packets.
Here's what I have so far:
```js
package com.shaybox.privateservers;

import com.github.steveice10.mc.auth.data.GameProfile;
import com.github.steveice10.mc.protocol.MinecraftProtocol;
import com.github.steveice10.mc.protocol.ServerLoginHandler;
import com.github.steveice10.mc.protocol.data.message.Message;
import com.github.steveice10.mc.protocol.data.message.TextMessage;
import com.github.steveice10.mc.protocol.data.status.PlayerInfo;
import com.github.steveice10.mc.protocol.data.status.ServerStatusInfo;
import com.github.steveice10.mc.protocol.data.status.VersionInfo;
import com.github.steveice10.mc.protocol.data.status.handler.ServerInfoBuilder;
import com.github.steveice10.mc.protocol.packet.ingame.client.ClientKeepAlivePacket;
import com.github.steveice10.mc.protocol.packet.ingame.server.ServerKeepAlivePacket;
import com.github.steveice10.mc.protocol.packet.login.client.LoginStartPacket;
import com.github.steveice10.packetlib.Client;
import com.github.steveice10.packetlib.Server;
import com.github.steveice10.packetlib.Session;
import com.github.steveice10.packetlib.event.server.ServerAdapter;
import com.github.steveice10.packetlib.event.server.SessionAddedEvent;
import com.github.steveice10.packetlib.event.session.DisconnectedEvent;
import com.github.steveice10.packetlib.event.session.PacketReceivedEvent;
import com.github.steveice10.packetlib.event.session.SessionAdapter;
import com.github.steveice10.packetlib.packet.Packet;
import com.github.steveice10.packetlib.tcp.TcpSessionFactory;

import static com.github.steveice10.mc.protocol.MinecraftConstants.*;
import static com.github.steveice10.mc.protocol.data.SubProtocol.GAME;

public class Main {
	private static Client remote = null;
	private static Session remoteSession = null;

	public static void main(String[] args) {
		Server server = new Server("0.0.0.0", 25566, MinecraftProtocol.class, new TcpSessionFactory(java.net.Proxy.NO_PROXY));

		VersionInfo versionInfo = new VersionInfo(GAME_VERSION, PROTOCOL_VERSION);
		PlayerInfo playerInfo = new PlayerInfo(1, 0, new GameProfile[0]);
		TextMessage textMessage = new TextMessage("Private Servers");
		final ServerStatusInfo serverStatusInfo = new ServerStatusInfo(versionInfo, playerInfo, textMessage, null);
		server.setGlobalFlag(SERVER_INFO_BUILDER_KEY, (ServerInfoBuilder) session -> serverStatusInfo);
		server.setGlobalFlag(SERVER_LOGIN_HANDLER_KEY, (ServerLoginHandler) session -> System.out.println("CALLED"));

		server.addListener(new ServerAdapter() {
			@Override
			public void sessionAdded(SessionAddedEvent sessionEvent) {
				final Session clientSession = sessionEvent.getSession();
				System.out.println("1");

				sessionEvent.getSession().addListener(new SessionAdapter() {
					@Override
					public void packetReceived(PacketReceivedEvent clientPacketEvent) {
						Packet clientPacket = clientPacketEvent.getPacket();

						if (clientPacket instanceof ClientKeepAlivePacket) return;

						System.out.println("2: " + clientPacket.toString());
						System.out.println("2: Client Mode: " + ((MinecraftProtocol) clientSession.getPacketProtocol()).getSubProtocol());
						if (remote != null)
							System.out.println("2: Remote Mode: " + ((MinecraftProtocol) remote.getSession().getPacketProtocol()).getSubProtocol());

						if (clientPacket instanceof LoginStartPacket) {
							String username = ((LoginStartPacket) clientPacket).getUsername();

							MinecraftProtocol minecraftProtocol = new MinecraftProtocol(username);
							remote = new Client("0.0.0.0", 25565, minecraftProtocol, new TcpSessionFactory(java.net.Proxy.NO_PROXY));
							remoteSession = remote.getSession();
							remoteSession.addListener(new SessionAdapter() {
								@Override
								public void packetReceived(PacketReceivedEvent remotePacketEvent) {
									Packet remotePacket = remotePacketEvent.getPacket();

									if (remotePacket instanceof ServerKeepAlivePacket) return;

									System.out.println("3: " + remotePacket.toString());
									System.out.println("3: Client Mode: " + ((MinecraftProtocol) clientSession.getPacketProtocol()).getSubProtocol());
									System.out.println("3: Remote Mode: " + ((MinecraftProtocol) remoteSession.getPacketProtocol()).getSubProtocol());

									if (((MinecraftProtocol) remoteSession.getPacketProtocol()).getSubProtocol() == GAME) {
										while (((MinecraftProtocol) clientSession.getPacketProtocol()).getSubProtocol() != GAME) {
											try {
												Thread.sleep(5);
											} catch (InterruptedException ignored) {
											}
										}

										clientSession.send(remotePacket);
									} else {
										System.out.println("Blocked: 3");
									}
								}

								@Override
								public void disconnected(DisconnectedEvent event) {
									clientSession.disconnect(event.getReason());
									System.out.println("Remote Disconnected: " + Message.fromString(event.getReason()).getFullText());
									if (event.getCause() != null) {
										event.getCause().printStackTrace();
									}
								}
							});
							remoteSession.connect();
							System.out.println("Remote Started: " + username);
						}

						if (remoteSession == null) {
							System.out.println("Blocked: 4");
							return;
						}

						if (((MinecraftProtocol) clientSession.getPacketProtocol()).getSubProtocol() == GAME) {
							while (((MinecraftProtocol) remoteSession.getPacketProtocol()).getSubProtocol() != GAME) {
								try {
									Thread.sleep(5);
								} catch (InterruptedException ignored) {
								}
							}

							remoteSession.send(clientPacket);
						} else {
							System.out.println("Blocked: 5");
						}
					}
				});

				clientSession.addListener(new SessionAdapter() {
					@Override
					public void disconnected(DisconnectedEvent event) {
						remoteSession.disconnect(event.getReason());
						System.out.println("Client Disconnected: " + Message.fromString(event.getReason()).getFullText());
						if (event.getCause() != null) {
							event.getCause().printStackTrace();
						}
					}
				});
			}
		});

		server.bind();
		System.out.println("Server Started");
	}
}
```

**Comment by Steveice10** [comment]
Making a fully working Minecraft protocol proxy is unfortunately something with more potential complexities than I can reasonably provide help with. One thing I would suggest is to make sure the session's MinecraftProtocol's state is set to INGAME when forwarding packets, so you don't end up forwarding handshake and login packets that MCProtocolLib itself already handles. You might also want to check out another project like BungeeCord (assuming that's still around; it's been a while) to see what kinds of edge cases it has to account for; or, if your JavaScript already works, you can simply replicate the kinds of behavior you implemented there.

**Comment by ShayBox** [comment]
Then could you tell me how to check the state of the session, I think that's the only thing left I can't figure out how to do

**Comment by ShayBox** [comment]
I have it mostly working now, but every packet I try and write just disconnects the actual client from the lib server because they're Unregistered outgoing packet class's, the first one is ServerJoinGamePacket, if I filter that one out and manually send a constructed one it has the same error on the next one it tries to send.

**Comment by ShayBox** [comment]
What packets does the lib send when a client connects to a server

**Comment by Steveice10** [comment]
There's an overview of the login process here: https://wiki.vg/Protocol_FAQ#What.27s_the_normal_login_sequence_for_a_client.3F

Everything up to "Login Success" is the handshake and login process handled by MCProtocolLib, and everything after is for the library user to do.

What you'd basically want to do is, when you get a SubProtocol.GAME packet from the server, you want to wait for the client to also be in SubProtocol.GAME, and then send the received packet to it. The same is true for packets sent by the client, except those are of course sent to the server.

**Comment by ShayBox** [comment]
Yeah, I have that, but for some reason my server (the actual game client) is never going to game state

**Comment by Steveice10** [comment]
Could you share code snippets of what you're currently doing?

**Comment by ShayBox** [comment]
I've been secretly updating the code in the first message to be up to date 😂

**Comment by Steveice10** [comment]
A few problems I've noticed:
* You shouldn't be forwarding LoginStartPacket or LoginSuccessPacket; that's part of the login handshake and is handled by MCProtocolLib.
* In the session provided by the server (the outer-most one), you should be sending to remoteSession (the client connecting to the real server), not clientSession (the real client connected to your proxy server).
* You check for ClientKeepAlivePacket in removeSession's listener (the inner-most one), but it's a client, so it will actually be receiving server packets, like ServerKeepAlivePacket.

**Comment by ShayBox** [comment]
Originally I didn't allow the login packets, but I tried to allow them to see if that was the problem
Didn't realize there was a ServerKeepAlivePacket

**Comment by ShayBox** [comment]
I'm pretty sure I am sending to clientSession
```java
Session clientSession = remote.getSession();
						if (((MinecraftProtocol) clientSession.getPacketProtocol()).getSubProtocol() == GAME) {
							clientSession.send(clientPacket);
						} else {
							System.out.println("Blocked: 5");
						}
```

**Comment by Steveice10** [comment]
Yeah, I noticed that a bit late and edited it out of my post; it's a bit ambiguously named, as you have clientSession at the top and then redefine it at the bottom.

**Comment by ShayBox** [comment]
Well I made those changes, and here's what I get, Unregistered outgoing packet class
![image](https://user-images.githubusercontent.com/9505196/44942195-6ceeba00-ad7a-11e8-9cb4-ddd3686d75b1.png)

**Comment by ShayBox** [comment]
Server Mode is Client Mode, forgot to change that

**Comment by Steveice10** [comment]
As logged, there's a mismatch of modes when you receive the ServerJoinGamePacket. You are already making sure that the source of the packet is in the right mode, but you also need to wait for the destination to be in the same mode before you forward the packet.

Actually, it seems the former check is also not completely correct. You should be checking the sub protocol of the clientSession outside the listener, but since you redefined clientSession, it's checking the wrong one.

**Comment by Steveice10** [comment]
I refreshed the page and noticed you changed it to "remoteSession" at the bottom. It still stands that you should be checking the sub-protocol of what is still clientSession, rather than remoteSession.

**Comment by Steveice10** [comment]
If you add in the [ServerLoginHandler from the example code](https://github.com/Steveice10/MCProtocolLib/blob/master/example/com/github/steveice10/mc/protocol/test/MinecraftProtocolTest.java#L64), does it ever get called?

**Comment by ShayBox** [comment]
Nope, never

**Comment by Steveice10** [comment]
Also, you should probably add methods for handling DisconnectedEvent to your listeners, in order to log if/when a disconnect occurs.

**Comment by ShayBox** [comment]
I added one, and made it exit on disconnect
```
Server Started
1
2: HandshakePacket(protocolVersion=401, hostname=localhost, port=25565, intent=LOGIN)
2: Client Mode: LOGIN
Blocked: 4
2: LoginStartPacket(username=ShayBox)
2: Client Mode: LOGIN
Remote Started: ShayBox
Blocked: 5
3: LoginSuccessPacket(profile=GameProfile{id=90259935-b113-34e8-b480-9d24b00df414, name=ShayBox, properties=[], textures={}})
3: Client Mode: LOGIN
3: Remote Mode: LOGIN
Blocked: 3
3: ServerJoinGamePacket(entityId=3832, hardcore=false, gamemode=SURVIVAL, dimension=0, difficulty=EASY, maxPlayers=20, worldType=DEFAULT, reducedDebugInfo=false)
3: Client Mode: LOGIN
3: Remote Mode: GAME
3: ServerPluginMessagePacket(channel=minecraft:brand, data=[6, 83, 112, 105, 103, 111, 116])
3: Client Mode: LOGIN
3: Remote Mode: GAME
3: ServerDifficultyPacket(difficulty=EASY)
3: Client Mode: LOGIN
3: Remote Mode: GAME
3: ServerPlayerAbilitiesPacket(invincible=false, canFly=false, flying=false, creative=false, flySpeed=0.05, walkSpeed=0.1)
3: Client Mode: LOGIN
3: Remote Mode: GAME
3: ServerPlayerChangeHeldItemPacket(slot=0)
3: Client Mode: LOGIN
3: Remote Mode: GAME
3: ServerDeclareRecipesPacket(data=byte[](length=43039))
3: Client Mode: LOGIN
3: Remote Mode: GAME
3: ServerDeclareTagsPacket(blockTags={minecraft:rails=[I@3f7b5acf, minecraft:birch_logs=[I@1967843c, minecraft:wooden_trapdoors=[I@220c4cc, minecraft:carpets=[I@5e508baa, minecraft:slabs=[I@3b981f8d, minecraft:saplings=[I@1efb2aa6, minecraft:stairs=[I@1a799b11, minecraft:wooden_doors=[I@402e4e2f, minecraft:jungle_logs=[I@3b3155d0, minecraft:planks=[I@7cd8e60a, minecraft:wooden_stairs=[I@2aaf5b93, minecraft:ice=[I@18c227df, minecraft:anvil=[I@29ec7ec2, minecraft:wall_corals=[I@12bf2543, minecraft:acacia_logs=[I@421c8744, minecraft:logs=[I@4b69ac07, minecraft:flower_pots=[I@139c1c6, minecraft:stone_bricks=[I@6ac7799f, minecraft:corals=[I@4c47e524, minecraft:enderman_holdable=[I@4ac8713f, minecraft:spruce_logs=[I@5b0ae51, minecraft:wooden_buttons=[I@546a34f9, minecraft:wool=[I@27779595, minecraft:banners=[I@2ebf59cd, minecraft:coral_plants=[I@2e7da86d, minecraft:wooden_slabs=[I@2bb58ca7, minecraft:doors=[I@30f57f79, minecraft:coral_blocks=[I@64d0399b, minecraft:dark_oak_logs=[I@27adcbac, minecraft:sand=[I@207aab4a, minecraft:valid_spawn=[I@3bef168b, minecraft:impermeable=[I@5e16fc8c, minecraft:trapdoors=[I@17afac49, minecraft:underwater_bonemeals=[I@627a750d, minecraft:leaves=[I@21e27c87, minecraft:oak_logs=[I@48f916ab, minecraft:buttons=[I@225e2619, minecraft:wooden_pressure_plates=[I@13bdfd42}, itemTags={minecraft:rails=[I@2189adf6, minecraft:birch_logs=[I@21c5bb22, minecraft:wooden_trapdoors=[I@72f82fed, minecraft:carpets=[I@ed38b1d, minecraft:slabs=[I@62d9612c, minecraft:saplings=[I@6e49dafe, minecraft:fishes=[I@5dfd079d, minecraft:stairs=[I@4f64f45c, minecraft:wooden_doors=[I@661d3c9d, minecraft:boats=[I@4623848a, minecraft:jungle_logs=[I@73d7b23c, minecraft:planks=[I@1bf97e0e, minecraft:wooden_stairs=[I@148f5038, minecraft:anvil=[I@4e5291f7, minecraft:acacia_logs=[I@5a8c53, minecraft:logs=[I@50838b58, minecraft:stone_bricks=[I@3e630fe0, minecraft:spruce_logs=[I@6464fcf2, minecraft:wooden_buttons=[I@3088cc39, minecraft:wool=[I@7c9d583b, minecraft:banners=[I@5aa75447, minecraft:wooden_slabs=[I@19e7a08d, minecraft:doors=[I@6f784e8c, minecraft:dark_oak_logs=[I@79329fd8, minecraft:sand=[I@19d7f9d5, minecraft:trapdoors=[I@3d10c1aa, minecraft:leaves=[I@10b1f4aa, minecraft:oak_logs=[I@7d90653b, minecraft:buttons=[I@5baf320d, minecraft:wooden_pressure_plates=[I@6089a543}, fluidTags={minecraft:lava=[I@7f02095c, minecraft:water=[I@1c5023a})
3: Client Mode: LOGIN
3: Remote Mode: GAME
3: ServerEntityStatusPacket(entityId=3832, status=PLAYER_OP_PERMISSION_LEVEL_0)
3: Client Mode: LOGIN
3: Remote Mode: GAME
3: ServerDeclareCommandsPacket(data=byte[](length=1286))
3: Client Mode: LOGIN
3: Remote Mode: GAME
3: ServerUnlockRecipesPacket(action=INIT, recipes=[minecraft:oak_boat, minecraft:acacia_boat, minecraft:spruce_boat, minecraft:jungle_boat, minecraft:birch_boat, minecraft:dark_oak_boat], alreadyKnownRecipes=[minecraft:oak_boat, minecraft:acacia_boat, minecraft:spruce_boat, minecraft:jungle_boat, minecraft:birch_boat, minecraft:dark_oak_boat], openCraftingBook=false, activateCraftingFiltering=false, openSmeltingBook=false, activateSmeltingFiltering=false)
3: Client Mode: LOGIN
3: Remote Mode: GAME
3: ServerChatPacket(message=TextMessage(text=, style=MessageStyle(color=white, formats=[], click=null, hover=null, insertion=null, parent=MessageStyle(color=white, formats=[], click=null, hover=null, insertion=null, parent=null)), extra=[TextMessage(text=ShayBox, style=MessageStyle(color=yellow, formats=[], click=null, hover=null, insertion=null, parent=MessageStyle(color=white, formats=[], click=null, hover=null, insertion=null, parent=MessageStyle(color=white, formats=[], click=null, hover=null, insertion=null, parent=null))), extra=[]), TextMessage(text= joined the game, style=MessageStyle(color=yellow, formats=[], click=null, hover=null, insertion=null, parent=MessageStyle(color=white, formats=[], click=null, hover=null, insertion=null, parent=MessageStyle(color=white, formats=[], click=null, hover=null, insertion=null, parent=null))), extra=[])]), type=SYSTEM)
3: Client Mode: LOGIN
3: Remote Mode: GAME
3: ServerPlayerListEntryPacket(action=ADD_PLAYER, entries=[PlayerListEntry(profile=GameProfile{id=90259935-b113-34e8-b480-9d24b00df414, name=ShayBox, properties=[], textures={}}, gameMode=SURVIVAL, ping=0, displayName=null)])
3: Client Mode: LOGIN
3: Remote Mode: GAME
3: ServerPlayerListEntryPacket(action=ADD_PLAYER, entries=[PlayerListEntry(profile=GameProfile{id=90259935-b113-34e8-b480-9d24b00df414, name=ShayBox, properties=[], textures={}}, gameMode=SURVIVAL, ping=0, displayName=null)])
3: Client Mode: LOGIN
3: Remote Mode: GAME
Client Disconnected: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unregistered outgoing packet class: com.github.steveice10.mc.protocol.packet.ingame.server.ServerJoinGamePacket
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unregistered outgoing packet class: com.github.steveice10.mc.protocol.packet.ingame.server.ServerJoinGamePacket
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
	at io.netty.handler.codec.ByteToMessageCodec.write(ByteToMessageCodec.java:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1081)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1128)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1070)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Unregistered outgoing packet class: com.github.steveice10.mc.protocol.packet.ingame.server.ServerJoinGamePacket
	at com.github.steveice10.packetlib.packet.PacketProtocol.getOutgoingId(PacketProtocol.java:141)
	at com.github.steveice10.packetlib.tcp.TcpPacketCodec.encode(TcpPacketCodec.java:26)
	at com.github.steveice10.packetlib.tcp.TcpPacketCodec.encode(TcpPacketCodec.java:16)
	at io.netty.handler.codec.ByteToMessageCodec$Encoder.encode(ByteToMessageCodec.java:172)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	... 13 more

Process finished with exit code 1
```

**Comment by Steveice10** [comment]
Can you try adding this before "if (((MinecraftProtocol) remoteSession.getPacketProtocol()).getSubProtocol() == GAME) {":
```
while(((MinecraftProtocol) clientSession.getPacketProtocol()).getSubProtocol() != GAME) {
    try {
        Thread.sleep(5);
    } catch(InterruptedException e) {
    }
}
```

**Comment by ShayBox** [comment]
Well, the game is stuck at Encrypting, it didn't disconnect from an unregistered error, and client mode is still login

**Comment by ShayBox** [comment]
Adding one to the other check keeps it at the success packet, but it never gets past that

**Comment by Steveice10** [comment]
Just tested your code on my machine. With a freshly setup 1.13.1 server with "online-mode=false" and a fresh, logged in 1.13.1 client, I was able to log in via the proxy successfully, and everything seemed to work just fine.

The only modifications I made to the code were to add my while loop before each invocation of send, waiting for clientSession before clientSession.send and waiting on remoteSession before remoteSession.send.

Here's the full code:
```
import com.github.steveice10.mc.auth.data.GameProfile;
import com.github.steveice10.mc.protocol.MinecraftProtocol;
import com.github.steveice10.mc.protocol.ServerLoginHandler;
import com.github.steveice10.mc.protocol.data.message.Message;
import com.github.steveice10.mc.protocol.data.message.TextMessage;
import com.github.steveice10.mc.protocol.data.status.PlayerInfo;
import com.github.steveice10.mc.protocol.data.status.ServerStatusInfo;
import com.github.steveice10.mc.protocol.data.status.VersionInfo;
import com.github.steveice10.mc.protocol.data.status.handler.ServerInfoBuilder;
import com.github.steveice10.mc.protocol.packet.ingame.client.ClientKeepAlivePacket;
import com.github.steveice10.mc.protocol.packet.ingame.server.ServerJoinGamePacket;
import com.github.steveice10.mc.protocol.packet.ingame.server.ServerKeepAlivePacket;
import com.github.steveice10.mc.protocol.packet.login.client.LoginStartPacket;
import com.github.steveice10.packetlib.Client;
import com.github.steveice10.packetlib.Server;
import com.github.steveice10.packetlib.Session;
import com.github.steveice10.packetlib.event.server.ServerAdapter;
import com.github.steveice10.packetlib.event.server.SessionAddedEvent;
import com.github.steveice10.packetlib.event.session.DisconnectedEvent;
import com.github.steveice10.packetlib.event.session.PacketReceivedEvent;
import com.github.steveice10.packetlib.event.session.SessionAdapter;
import com.github.steveice10.packetlib.packet.Packet;
import com.github.steveice10.packetlib.tcp.TcpSessionFactory;

import static com.github.steveice10.mc.protocol.MinecraftConstants.*;
import static com.github.steveice10.mc.protocol.data.SubProtocol.GAME;
import static com.github.steveice10.mc.protocol.data.game.entity.player.GameMode.SURVIVAL;
import static com.github.steveice10.mc.protocol.data.game.setting.Difficulty.PEACEFUL;
import static com.github.steveice10.mc.protocol.data.game.world.WorldType.DEFAULT;

public class MinecraftProtocolTest {
    private static Client remote = null;
    private static Session remoteSession = null;

    public static void main(String[] args) {
        Server server = new Server("0.0.0.0", 25565, MinecraftProtocol.class, new TcpSessionFactory(java.net.Proxy.NO_PROXY));

        VersionInfo versionInfo = new VersionInfo(GAME_VERSION, PROTOCOL_VERSION);
        PlayerInfo playerInfo = new PlayerInfo(1, 0, new GameProfile[0]);
        TextMessage textMessage = new TextMessage("Private Servers");
        final ServerStatusInfo serverStatusInfo = new ServerStatusInfo(versionInfo, playerInfo, textMessage, null);
        server.setGlobalFlag(SERVER_INFO_BUILDER_KEY, new ServerInfoBuilder() {
            @Override
            public ServerStatusInfo buildInfo(Session session) {
                return serverStatusInfo;
            }
        });

        server.setGlobalFlag(SERVER_LOGIN_HANDLER_KEY, new ServerLoginHandler() {
            @Override
            public void loggedIn(Session session) {
                System.out.println("CALLED");
            }
        });

        server.addListener(new ServerAdapter() {
            @Override
            public void sessionAdded(SessionAddedEvent sessionEvent) {
                final Session clientSession = sessionEvent.getSession();
                System.out.println("1");

                sessionEvent.getSession().addListener(new SessionAdapter() {
                    @Override
                    public void packetReceived(PacketReceivedEvent clientPacketEvent) {
                        Packet clientPacket = clientPacketEvent.getPacket();

                        if (clientPacket instanceof ClientKeepAlivePacket) return;

                        System.out.println("2: " + clientPacket.toString());
                        System.out.println("2: Client Mode: " + ((MinecraftProtocol) clientSession.getPacketProtocol()).getSubProtocol());
                        if (remote != null)
                            System.out.println("2: Remote Mode: " + ((MinecraftProtocol) remote.getSession().getPacketProtocol()).getSubProtocol());

                        if (clientPacket instanceof LoginStartPacket) {
                            String username = ((LoginStartPacket) clientPacket).getUsername();

                            MinecraftProtocol minecraftProtocol = new MinecraftProtocol(username);
                            remote = new Client("0.0.0.0", 25566, minecraftProtocol, new TcpSessionFactory(java.net.Proxy.NO_PROXY));
                            remoteSession = remote.getSession();
                            remoteSession.addListener(new SessionAdapter() {
                                @Override
                                public void packetReceived(PacketReceivedEvent remotePacketEvent) {
                                    Packet remotePacket = remotePacketEvent.getPacket();

                                    if (remotePacket instanceof ServerKeepAlivePacket) return;

//									System.out.println("3: " + remotePacket.toString());
//									System.out.println("3: Client Mode: " + ((MinecraftProtocol) clientSession.getPacketProtocol()).getSubProtocol());
//									System.out.println("3: Remote Mode: " + ((MinecraftProtocol) remoteSession.getPacketProtocol()).getSubProtocol());

                                    if (((MinecraftProtocol) remoteSession.getPacketProtocol()).getSubProtocol() == GAME) {
                                        while(((MinecraftProtocol) clientSession.getPacketProtocol()).getSubProtocol() != GAME) {
                                            try {
                                                Thread.sleep(5);
                                            } catch(InterruptedException e) {
                                            }
                                        }

                                        clientSession.send(remotePacket);
                                    } else {
                                        System.out.println("Blocked: 3");
                                    }
                                }

                                @Override
                                public void disconnected(DisconnectedEvent event) {
                                    System.out.println("Remote Disconnected: " + Message.fromString(event.getReason()).getFullText());
                                    if(event.getCause() != null) {
                                        event.getCause().printStackTrace();
                                    }
                                }
                            });
                            remoteSession.connect();
                            System.out.println("Remote Started: " + username);
                        }

                        if (remoteSession == null) {
                            System.out.println("Blocked: 4");
                            return;
                        }

                        if (((MinecraftProtocol) clientSession.getPacketProtocol()).getSubProtocol() == GAME) {
                            while(((MinecraftProtocol) remoteSession.getPacketProtocol()).getSubProtocol() != GAME) {
                                try {
                                    Thread.sleep(5);
                                } catch(InterruptedException e) {
                                }
                            }

                            remoteSession.send(clientPacket);
                        } else {
                            System.out.println("Blocked: 5");
                        }
                    }
                });

                clientSession.addListener(new SessionAdapter() {
                    @Override
                    public void disconnected(DisconnectedEvent event) {
                        System.out.println("Client Disconnected: " + Message.fromString(event.getReason()).getFullText());
                        if(event.getCause() != null) {
                            event.getCause().printStackTrace();
                        }
                    }
                });
            }
        });

        server.bind();
        System.out.println("Server Started");
    }
}
```

**Comment by ShayBox** [comment]
Yep, that worked for me too 👍 Thank you so much!

**Comment by Steveice10** [comment]
No problem. I actually just found a protocol bug through testing this, so it's been pretty helpful.

**Comment by ShayBox** [comment]
Should be the last question, how do I specify a version to a client so It can connect to an older server

**Comment by ShayBox** [comment]
Nvm, it's weird, I set the server to "1.13" 393, but when trying to connect says my client is old, yet if I try on 1.13.1 client, it says the same thing 🤔 maybe that's the bug you were talking about

**Comment by ShayBox** [comment]
This proxy also seems to have the same problem the JS version has, but a lot worse, this has noticeable lag, and lots of packets causes disconnection

**Comment by Steveice10** [comment]
You probably shouldn't go changing the version string and protocol version number, as there may be incompatibilities between the current code and previous versions of the protocol.

As for packets causing disconnection, if you see any glaring exceptions output to the log, such as those for keys or values not having mappings, make sure to report them to the issue tracker so they can be looked at.

**Comment by ShayBox** [comment]
You do know you're supposed to keep the old working code so you can change it to go back right, not remove it.

And I mean lots of packets as in not individual packets causing disconnection, but lots of them causes it to not send them fast enough and disconnect, and the delay between sending them is noticeable, at least 1sec between it getting to the server, and server back. How would I fix that

**Comment by Steveice10** [comment]
No, protocol code is not supposed to be retained between versions, as it would be far too complex to design a good API around tons of duplicated packet classes to account for every protocol change. Some packets have been completely revised between versions, for example. If you want to use an older protocol version, you need to use the corresponding library version.

As for the delays, I'm not sure there's much I can do to help with that. On my system it seemed to run perfectly fine with no noticeable lag, despite running both a client and a server on a budget laptop, and if you're getting similar lag even with your javascript solution, I don't think its necessarily a MCProtocolLib problem.

**Comment by ShayBox** [comment]
No, there's no lag on the js version, and I have a proxy written using this lib that works fine, but this proxy has lag, and suffers from the same problem as the js version, sending/receiving lots of packets will cause them to disconnect because it cant keep up transferring them, the js version does that because it can only do one packet at a time, while you're handling one packet it blocks the rest, this lib doesn't do that but seems worse in that regard, less amounts of packets will cause it, may be related to the lag i'm noticing

**Comment by Steveice10** [comment]
I suppose the biggest issue with regards to speed would be that MCProtocolLib parses packet data to give a higher level representation of the contained data, giving it more overhead than your other solution that simply passes the raw data through. The library is more geared towards use cases that can make use of the parsed information, rather than a simple man-in-the-middle proxy. Once again, though, I played around a bit on a local server and it seemed to work just fine for me.

**Comment by ShayBox** [comment]
yeah, I have a proxy someone wrote with this lib and it's perfect, though uses 1.12, still should work just fine, and that one even had to interpret the packets because it wanted to stay logged in to the end server 24/7 and let the user disconnect whenever they wanted.

And I did notice that particle packet crash, and piston extension too

**Comment by ShayBox** [comment]
Updating the lib didn't fix the piston extension one, but did fix the particle one, also it seems to have fixed the delay 👍

**Comment by Steveice10** [comment]
The piston bug should be fixed now.

If you have the source to that proxy that works fine for you, you could try building it against the latest commit and see if it works with 1.13.1.

**Comment by ShayBox** [comment]
It won't, it's not updated to work with 1.13, it actually has to interpret the packets and reconstruct them, bit more advanced, but even doing that was able to do it with no delay, so I think something is wrong with my project

**Comment by Steveice10** [comment]
Something else you could try, then, is compiling the simple proxy against a 1.12 MCProtocolLib version and seeing how well that works. If it works better in 1.12 than 1.13, then I'll need to dig into the update commits again to look for the problem.

**Comment by ShayBox** [comment]
Build the update, pistons and particles still crashing

I can try that, but how am I supposed to build that, its not in a branch or included in the source that could be build with an option, it's completely removed from the source code of the project

**Comment by Steveice10** [comment]
Odd, that shouldn't be happening anymore. I've pushed another two commits that should make it completely impossible for that to happen.

**Comment by ShayBox** [comment]
Well running mvn clean install on all 5 libs and re-importing them, it still happens

**Comment by Steveice10** [comment]
You made sure to pull in the very latest commit, right?

**Comment by ShayBox** [comment]
Ah, I did forget to do that, my bad. those are fixed, the last issue is the delay, i'll try and figure out how to pull all 4 of the libs back to 1.12 and see if its working there

**Comment by Steveice10** [comment]
Alright. Checking out the commit of MCProtocolLib I mentioned should suffice; the PacketLib, Netty, and GSON versions haven't changed since then.

**Comment by ShayBox** [comment]
Still happens on 1.12, must be something i'm doing to cause it to be delayed

**Comment by Steveice10** [comment]
Have you tried commenting out any println calls? Debug output tends to add more overhead.

**Comment by ShayBox** [comment]
Yep, stills happens, it seems to handle packets in a burst

**Comment by ShayBox** [comment]
Here's a video of it https://youtu.be/r0sFvcC_lZA

**Comment by Steveice10** [comment]
Same here. Here's a video of how it runs on my laptop. Pardon some of the intermittent lag, as I'm running a Minecraft client, a Minecraft server, my IDE, and a screen recorder, all at the same time.

https://www.youtube.com/watch?v=C4EKgLSM1eA

**Comment by ShayBox** [comment]
Hmm, that's weird, there's no lag for you... maybe it's my windows, I did notice you're using linux, let me install linux real quick and test it, well "quick" i'll be back in a few hours

**Comment by ShayBox** [comment]
Nope, still does it on a different OS too, this is very weird... are you using language level 8?

**Comment by Steveice10** [comment]
I'm actually using language level 7, if you want to try that.

**Comment by ShayBox** [comment]
Nope, that's not it :/

**Comment by ShayBox** [comment]
I can't figure it out, maybe it's something to do with my project, do you see anything wrong with how this is configured? 
[Private Servers.zip](https://github.com/Steveice10/MCProtocolLib/files/2342763/Private.Servers.zip)

**Comment by Steveice10** [comment]
Should be fixed now, thanks.
